# Route de la page d'Accueil
index:
    path: /
    controller: App\Controller\ProStageController::index
# Route de la page qui affiche les stages selon l'entreprise
entreprise:
    path: /entreprise
    controller: App\Controller\ProStageController::entreprise
# Route de la page qui affiche les stages selon la formation
formation:
    path: /formation
    controller: App\Controller\ProStageController::formation
#Route de la page permettant de voir un stage en détail
stage:
    path: /stage/{id}
    controller: App\Controller\ProStageController::stage
#Route de la page permettant de voir les stages proposés par une entreprise
stageEntreprise:
    path: /entreprise/{nomEntreprise}
    controller: App\Controller\ProStageController::stageEntreprise
#Route de la page permettant de voir les stages proposés dans une formation
stageFormation:
    path: /formation/{nomFormation}
    controller: App\Controller\ProStageController::stageFormation
#Route permettant l'ajour d'une entreprise en base de données
ajoutEntreprise:
    path: /entrepriseAjouter
    controller: App\Controller\ProStageController::ajouterEntreprise
