index:
    path: /
    controller: App\Controller\ProStageController::index
entreprise:
    path: /entreprise
    controller: App\Controller\ProStageController::entreprise
formation:
    path: /formation
    controller: App\Controller\ProStageController::formation
stage:
    path: /stage/{id}
    controller: App\Controller\ProStageController::stage
